---
- hosts: metmini-itg
  become: yes
  tasks:

    - name: Run mysql_install_db
      command: mysql_install_db --datadir=/data/db

    - name: Start MariaDB service
      service: name=mariadb state=started enabled=yes

    - name: Is root password set?
      command: mysql -u root --execute "SELECT NOW()"
      register: is_root_password_set
      ignore_errors: yes

    - name: Set root password
      mysql_user: user=root password="secretsql" host=localhost
      when: is_root_password_set.rc == 0
